# Generated by Django 3.2.20 on 2024-01-15 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=16)),
                ('items_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=16, null=True)),
                ('final_items_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=16, null=True)),
                ('promo_code_discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=16, null=True)),
                ('promo_code_discount_percentage', models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=5, null=True)),
                ('final_total_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=16, null=True)),
                ('reference', models.CharField(blank=True, editable=False, max_length=14, unique=True)),
                ('payment_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payment', to='app.order')),
            ],
        ),
    ]
