# Generated by Django 3.2.20 on 2024-02-25 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Support', 'Support'), ('Billing', 'Billing'), ('Abuse', 'Abuse'), ('OTP', 'OTP'), ('Payments', 'Payments'), ('Transactions', 'Transactions'), ('Payouts', 'Payouts'), ('Services', 'Services'), ('Credit Points', 'Credit Points'), ('Account Funds', 'Account Funds'), ('Referrals', 'Referrals'), ('Others', 'Others')], max_length=225, null=True)),
                ('subject', models.CharField(blank=True, max_length=225, null=True)),
                ('message', models.TextField(blank=True, max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
