# Generated by Django 3.2.20 on 2024-02-14 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewpaidadseller',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_ad_seller_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewpaidadseller',
            name='seller_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_ad_seller_account_review', to='marketplace.marketplaceselleraccount'),
        ),
        migrations.AddField(
            model_name='reviewpaidadseller',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_paid_ad_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewfreeadseller',
            name='free_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_ad_reivew', to='marketplace.postfreead'),
        ),
        migrations.AddField(
            model_name='reviewfreeadseller',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_ad_seller_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewfreeadseller',
            name='seller_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_ad_seller_account_reivew', to='marketplace.marketplaceselleraccount'),
        ),
        migrations.AddField(
            model_name='reviewfreeadseller',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_free_ad_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportpaidad',
            name='paid_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_ad_report', to='marketplace.postpaidad'),
        ),
        migrations.AddField(
            model_name='reportpaidad',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_ad_reporter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportfreead',
            name='free_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_ad_report', to='marketplace.postfreead'),
        ),
        migrations.AddField(
            model_name='reportfreead',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fre_ad_reporter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postpaidad',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_ad_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postfreead',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paysofterapikey',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paysofter_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paidadmessageid',
            name='paid_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_ad_message_id', to='marketplace.postpaidad'),
        ),
        migrations.AddField(
            model_name='paidadmessageid',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_ad_message_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='free_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_ad_message', to='marketplace.postfreead'),
        ),
        migrations.AddField(
            model_name='message',
            name='free_ad_message_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freead_message_id', to='marketplace.freeadmessageid'),
        ),
        migrations.AddField(
            model_name='message',
            name='paid_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_ad_message', to='marketplace.postpaidad'),
        ),
        migrations.AddField(
            model_name='message',
            name='paid_ad_message_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paidad_message_id', to='marketplace.paidadmessageid'),
        ),
        migrations.AddField(
            model_name='message',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplacesellerphoto',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplaceselleraccount',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_account_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freeadmessageid',
            name='free_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_ad_message_id', to='marketplace.postfreead'),
        ),
        migrations.AddField(
            model_name='freeadmessageid',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_ad_message_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
