# Generated by Django 3.2.20 on 2024-01-15 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postpaidad',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_ad_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postfreead',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paysofterapikey',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paysofter_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='free_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_ad_message', to='marketplace.postfreead'),
        ),
        migrations.AddField(
            model_name='message',
            name='paid_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_ad_message', to='marketplace.postpaidad'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplacesellerphoto',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplaceselleraccount',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_account_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
