# Generated by Django 3.2.20 on 2024-01-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfreead',
            name='ad_category',
            field=models.CharField(choices=[('Home Appliances', 'Home Appliances'), ('Properties', 'Properties'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Vehicles', 'Vehicles'), ('Services', 'Services'), ('Mobile Phones', 'Mobile Phones'), ('Health & Beauty', 'Health & Beauty'), ('Sports', 'Sports'), ('Jobs', 'Jobs'), ('Babies and Kids', 'Babies and Kids'), ('Agric & Food', 'Agric & Food'), ('Repairs', 'Repairs'), ('Equipment & Tools', 'Equipment & Tools'), ('CVs', 'CVs'), ('Pets', 'Pets'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postfreead',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postfreead',
            name='state_province',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
