# Generated by Django 3.2.20 on 2024-02-14 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0004_totaladcharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdChargeTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ad_charges', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('total_ad_charge_hours', models.PositiveIntegerField(default=0, editable=False, null=True)),
                ('total_ad_charge_id', models.CharField(max_length=20, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('paid_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='total_ad_charge', to='marketplace.postpaidad')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_total_charge_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TotalAdCharge',
        ),
    ]
