# Generated by Django 3.2.20 on 2024-01-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20240120_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfreead',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='postpaidad',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
