# Generated by Django 3.2.20 on 2024-02-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20240214_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpaidad',
            name='ad_charge_is_owed',
            field=models.BooleanField(default=False),
        ),
    ]
