# Generated by Django 3.2.20 on 2024-02-17 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_postpaidad_ad_charge_is_owed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpaidad',
            name='ad_charge_is_owed',
        ),
    ]
