# Generated by Django 3.2.20 on 2024-02-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_remove_postpaidad_ad_charge_is_owed'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfreead',
            name='show_strike_through_promo_price',
            field=models.BooleanField(default=False),
        ),
    ]
