# Generated by Django 3.2.20 on 2024-01-22 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0008_auto_20240122_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfreead',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fre_ad_reporter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postpaidad',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_ad_reporter', to=settings.AUTH_USER_MODEL),
        ),
    ]
