# Generated by Django 3.2.20 on 2024-02-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_postfreead_show_strike_through_promo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfreead',
            name='count_in_stock',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='postpaidad',
            name='count_in_stock',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
