# Generated by Django 3.2.20 on 2024-01-22 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0009_auto_20240122_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfreead',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postpaidad',
            name='user',
        ),
        migrations.CreateModel(
            name='ReportPaidAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_report', models.CharField(blank=True, choices=[('Misleading Content', 'False or deceptive information in the ad, claims that are not substantiated.'), ('Inappropriate Content', 'Offensive language, images, or themes; content violating community standards or guidelines.'), ('Irrelevant or Unwanted Ads', 'Ads that are not relevant to the user; too frequent display of the same ad.'), ('Malware or Phishing', 'Ads containing malicious software or links to phishing websites.'), ('Privacy Concerns', 'Collection of personal information without consent; violation of privacy policies.'), ('Low-Quality or Unprofessional Design', 'Poorly designed or unprofessional-looking ads.'), ('Counterfeit or Fraudulent Products', 'Ads promoting counterfeit goods or fraudulent services.'), ('Political or Social Issues', 'Ads perceived as promoting hate speech, discrimination, or controversial political content.'), ('Technical Issues', 'Broken links or malfunctioning interactive elements in the ad.'), ('Unsolicited or Spammy Ads', 'Ads that appear as spam or unsolicited marketing messages.'), ('Disallowed Content', 'Ads promoting content that violates platform policies or legal regulations.'), ('Unverified Claims', 'Ads making claims that cannot be verified or proven.'), ('Unrealistic Promises', 'Ads promising unrealistic results or benefits.')], max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('paid_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_ad_report', to='marketplace.postpaidad')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_ad_reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportFreeAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_report', models.CharField(blank=True, choices=[('Misleading Content', 'False or deceptive information in the ad, claims that are not substantiated.'), ('Inappropriate Content', 'Offensive language, images, or themes; content violating community standards or guidelines.'), ('Irrelevant or Unwanted Ads', 'Ads that are not relevant to the user; too frequent display of the same ad.'), ('Malware or Phishing', 'Ads containing malicious software or links to phishing websites.'), ('Privacy Concerns', 'Collection of personal information without consent; violation of privacy policies.'), ('Low-Quality or Unprofessional Design', 'Poorly designed or unprofessional-looking ads.'), ('Counterfeit or Fraudulent Products', 'Ads promoting counterfeit goods or fraudulent services.'), ('Political or Social Issues', 'Ads perceived as promoting hate speech, discrimination, or controversial political content.'), ('Technical Issues', 'Broken links or malfunctioning interactive elements in the ad.'), ('Unsolicited or Spammy Ads', 'Ads that appear as spam or unsolicited marketing messages.'), ('Disallowed Content', 'Ads promoting content that violates platform policies or legal regulations.'), ('Unverified Claims', 'Ads making claims that cannot be verified or proven.'), ('Unrealistic Promises', 'Ads promising unrealistic results or benefits.')], max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('free_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_ad_report', to='marketplace.postfreead')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fre_ad_reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
