# Generated by Django 3.2.20 on 2024-02-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_auto_20240227_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfreead',
            name='show_strike_through_promo_price',
        ),
        migrations.AddField(
            model_name='postpaidad',
            name='show_strike_through_promo_price',
            field=models.BooleanField(default=False),
        ),
    ]
