# Generated by Django 3.2.20 on 2024-03-16 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0010_auto_20240227_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidAdMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('buyer_paid_ad_msg_count', models.PositiveIntegerField(default=0, editable=False)),
                ('seller_paid_ad_msg_count', models.PositiveIntegerField(default=0, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_message_buyer', to=settings.AUTH_USER_MODEL)),
                ('paid_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_ad_mgs', to='marketplace.postpaidad')),
                ('paid_ad_message_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_ad_mgs_id', to='marketplace.paidadmessageid')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_message_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreeAdMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('buyer_free_ad_msg_count', models.PositiveIntegerField(default=0, editable=False)),
                ('seller_free_ad_msg_count', models.PositiveIntegerField(default=0, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_message_buyer', to=settings.AUTH_USER_MODEL)),
                ('free_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_ad_mgs', to='marketplace.postfreead')),
                ('free_ad_message_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_ad_mgs_id', to='marketplace.freeadmessageid')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_message_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
