# Generated by Django 3.2.20 on 2024-01-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_auto_20240122_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfreead',
            name='ad_report_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='postpaidad',
            name='ad_report_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
