# Generated by Django 3.2.20 on 2024-03-16 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0011_freeadmessage_paidadmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
