# Generated by Django 3.2.20 on 2024-03-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_message_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='buyer_free_ad_msg_count',
        ),
        migrations.RemoveField(
            model_name='message',
            name='buyer_paid_ad_msg_count',
        ),
        migrations.RemoveField(
            model_name='message',
            name='seller_free_ad_msg_count',
        ),
        migrations.RemoveField(
            model_name='message',
            name='seller_paid_ad_msg_count',
        ),
        migrations.AddField(
            model_name='freeadmessageid',
            name='buyer_free_ad_msg_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='freeadmessageid',
            name='seller_free_ad_msg_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='paidadmessageid',
            name='buyer_paid_ad_msg_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='paidadmessageid',
            name='seller_paid_ad_msg_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
