# Generated by Django 3.2.20 on 2024-01-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_alter_marketplaceselleraccount_business_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceselleraccount',
            name='business_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
