# Generated by Django 3.2.20 on 2024-03-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_auto_20240317_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeadmessageid',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paidadmessageid',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
