# Generated by Django 3.2.20 on 2024-01-24 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0014_alter_marketplaceselleraccount_business_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
