# Generated by Django 3.2.20 on 2024-06-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_marketplaceselleraccount_follow_seller_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceselleraccount',
            name='follow_seller_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
