# Generated by Django 3.2.20 on 2024-01-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_message_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfreead',
            name='ad_is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postpaidad',
            name='ad_is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
