# Generated by Django 4.2.3 on 2024-08-24 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0016_alter_marketplaceselleraccount_follow_seller_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplaceselleraccount',
            name='is_seller_verified',
        ),
        migrations.AddField(
            model_name='marketplaceselleraccount',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_verified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
