# Generated by Django 3.2.20 on 2024-01-31 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0017_reviewfreeadseller_reviewpaidadseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewfreeadseller',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_ad_seller_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewpaidadseller',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_ad_seller_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
