# Generated by Django 3.2.20 on 2024-01-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_auto_20240131_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewfreeadseller',
            name='is_review_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewfreeadseller',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reviewfreeadseller',
            name='review_like_count',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reviewpaidadseller',
            name='is_review_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewpaidadseller',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reviewpaidadseller',
            name='review_like_count',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
