# Generated by Django 3.2.20 on 2024-01-31 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_auto_20240131_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewfreeadseller',
            name='seller_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_ad_seller_account_reivew', to='marketplace.marketplaceselleraccount'),
        ),
        migrations.AddField(
            model_name='reviewpaidadseller',
            name='seller_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_ad_seller_account_review', to='marketplace.marketplaceselleraccount'),
        ),
    ]
