# Generated by Django 3.2.20 on 2024-01-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_auto_20240131_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceselleraccount',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
