# Generated by Django 3.2.20 on 2024-02-02 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0021_marketplaceselleraccount_review_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_charges', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('paid_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_charge', to='marketplace.postpaidad')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_charge_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
