# Generated by Django 3.2.20 on 2024-02-07 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_freeadmessageid_paidadmessageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeadmessageid',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_ad_message', to='marketplace.message'),
        ),
        migrations.AlterField(
            model_name='paidadmessageid',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_ad_message', to='marketplace.message'),
        ),
    ]
