# Generated by Django 3.2.20 on 2024-02-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_auto_20240207_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeadmessageid',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paidadmessageid',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
