# Generated by Django 3.2.20 on 2024-02-07 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_auto_20240207_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeadmessageid',
            name='free_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_ad_message_idd', to='marketplace.postfreead'),
        ),
        migrations.AddField(
            model_name='message',
            name='free_ad_message_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freead_message_id', to='marketplace.freeadmessageid'),
        ),
        migrations.AddField(
            model_name='message',
            name='paid_ad_message_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paidad_message_id', to='marketplace.paidadmessageid'),
        ),
        migrations.AddField(
            model_name='paidadmessageid',
            name='paid_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_ad_message_id', to='marketplace.postpaidad'),
        ),
        migrations.AlterField(
            model_name='freeadmessageid',
            name='free_ad_message_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='freeadmessageid',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paidadmessageid',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paidadmessageid',
            name='paid_ad_message_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
