# Generated by Django 3.2.20 on 2024-02-08 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_auto_20240207_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeadmessageid',
            name='free_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_ad_message_id', to='marketplace.postfreead'),
        ),
    ]
