# Generated by Django 3.2.20 on 2024-02-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_alter_freeadmessageid_free_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='buyer_free_ad_msg_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='message',
            name='buyer_paid_ad_msg_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='message',
            name='seller_free_ad_msg_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='message',
            name='seller_paid_ad_msg_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
