# Generated by Django 3.2.20 on 2024-02-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_message_inbox', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessageinbox',
            name='msg_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
