# Generated by Django 3.2.20 on 2024-03-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportticket_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
