# Generated by Django 3.2.20 on 2024-03-21 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0004_supportticket_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportresponse',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='supportticket',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='supportresponse',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_user_response', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='admin_user_msg_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user_msg_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
