# Generated by Django 3.2.20 on 2024-02-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ad_charge_is_owed',
            field=models.BooleanField(default=False),
        ),
    ]
