# Generated by Django 3.2.20 on 2024-01-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_auto_20240126_1103'),
        ('user_profile', '0002_auto_20240126_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_paid_ads',
            field=models.ManyToManyField(editable=False, related_name='saved_paid_ads', to='marketplace.PostPaidAd'),
        ),
        migrations.AlterField(
            model_name='user',
            name='viewed_free_ads',
            field=models.ManyToManyField(editable=False, related_name='viewed_free_ads', to='marketplace.PostFreeAd'),
        ),
    ]
