# Generated by Django 3.2.20 on 2024-06-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_marketplaceselleraccount_follow_seller_count'),
        ('user_profile', '0005_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_followers',
            field=models.ManyToManyField(editable=False, related_name='seller_followers', to='marketplace.MarketPlaceSellerAccount'),
        ),
    ]
