# Generated by Django 3.2.20 on 2024-06-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_user_seller_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_followed_seller',
            field=models.BooleanField(default=False),
        ),
    ]
