# Generated by Django 3.2.20 on 2024-06-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_marketplaceselleraccount_follow_seller_count'),
        ('user_profile', '0007_user_is_followed_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_sellers',
            field=models.ManyToManyField(related_name='followed_sellers', to='marketplace.MarketPlaceSellerAccount'),
        ),
        migrations.AlterField(
            model_name='user',
            name='seller_followers',
            field=models.ManyToManyField(related_name='seller_followers', to='marketplace.MarketPlaceSellerAccount'),
        ),
    ]
