# Generated by Django 3.2.20 on 2024-06-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_alter_marketplaceselleraccount_follow_seller_count'),
        ('user_profile', '0008_auto_20240613_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_sellers',
            field=models.ManyToManyField(editable=False, related_name='followed_sellers', to='marketplace.MarketPlaceSellerAccount'),
        ),
        migrations.AlterField(
            model_name='user',
            name='seller_followers',
            field=models.ManyToManyField(editable=False, related_name='seller_followers', to='marketplace.MarketPlaceSellerAccount'),
        ),
    ]
