# Generated by Django 4.2.3 on 2024-08-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20240614_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_seller_account_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_seller_account_verified',
            field=models.BooleanField(default=False),
        ),
    ]
