# Generated by Django 3.2.20 on 2024-05-14 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellCreditPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('cps_sell_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('buyer_old_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('buyer_new_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seller_old_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seller_new_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_credit_point', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_credit_point', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CpsBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cps_bonus_type', models.CharField(blank=True, choices=[('Referral Bonus', 'Referral Bonus'), ('Sign-up Bonus', 'Sign-up Bonus'), ('Birthday Bonus', 'Birthday Bonus'), ('Loyalty Bonus', 'Loyalty Bonus'), ('Earned Bonus', 'Earned Bonus'), ('Other Bonus', 'Other Bonus')], editable=False, max_length=100, null=True)),
                ('cps_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('cps_bonus_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('old_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cps_bonus_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyUsdCreditPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, choices=[('1', '1,000 cps for USD 1'), ('5', '5,200 cps for USD 5'), ('10', '10,800 cps for USD 10'), ('15', '16,500 cps for USD 15'), ('20', '24,000 cps for USD 20'), ('60', '60,000 cps for USD 50'), ('100', '125,000 cps for USD 100'), ('200', '255,000 cps for USD 200'), ('500', '700,000 cps for USD 500'), ('1000', '1,500,000 cps for USD 1,000')], editable=False, max_length=100, null=True)),
                ('cps_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('usd_cps_purchase_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('old_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usd_cps_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyCreditPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, choices=[('500', '500 cps for NGN 500'), ('1000', '1,000 cps for NGN 1,000'), ('5000', '5,200 cps for NGN 5,000'), ('10000', '10,800 cps for NGN 10,000'), ('15000', '16,500 cps for NGN 15,000'), ('20000', '24,000 cps for NGN 20,000'), ('60000', '60,000 cps for NGN 50,000'), ('100000', '125,000 cps for NGN 100,000'), ('200000', '255,000 cps for NGN 200,000'), ('500000', '700,000 cps for NGN 500,000'), ('1000000', '1,500,000 cps for NGN 1,000,000')], editable=False, max_length=100, null=True)),
                ('cps_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('cps_purchase_id', models.CharField(max_length=20, unique=True)),
                ('old_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_credit_point_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdChargeCreditPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cps_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('ad_charge_cps_id', models.CharField(max_length=20, unique=True)),
                ('old_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_charge_credit_point_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
