# Generated by Django 3.2.20 on 2024-01-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyCreditPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, choices=[('500', '500 cps for NGN 500'), ('1000', '1,000 cps for NGN 1,000'), ('5000', '5,200 cps for NGN 5,000'), ('10000', '10,800 cps for NGN 10,000'), ('15000', '16,500 cps for NGN 15,000'), ('20000', '24,000 cps for NGN 20,000'), ('60000', '60,000 cps for NGN 50,000'), ('100000', '125,000 cps for NGN 100,000'), ('200000', '255,000 cps for NGN 200,000'), ('500000', '700,000 cps for NGN 500,000'), ('1000000', '1,500,000 cps for NGN 1,000,000')], editable=False, max_length=100, null=True)),
                ('cps_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('cps_purchase_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyUsdCreditPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, choices=[('1', '1,000 cps for USD 1'), ('5', '5,200 cps for USD 5'), ('10', '10,800 cps for USD 10'), ('15', '16,500 cps for USD 15'), ('20', '24,000 cps for USD 20'), ('60', '60,000 cps for USD 50'), ('100', '125,000 cps for USD 100'), ('200', '255,000 cps for USD 200'), ('500', '700,000 cps for USD 500'), ('1000', '1,500,000 cps for USD 1,000')], editable=False, max_length=100, null=True)),
                ('cps_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('usd_cps_purchase_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditPointEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_points_earned', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditPointPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_points_earned', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('referral_credit_points_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditPointRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('credit_point_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('request_ref', models.CharField(blank=True, max_length=10, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellCreditPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('cps_sell_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
