# Generated by Django 3.2.20 on 2024-05-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_point', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellcreditpoint',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=50),
        ),
    ]
