# Generated by Django 3.2.20 on 2024-01-15 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit_point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellcreditpoint',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_credit_point', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellcreditpoint',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_credit_point', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditpointrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_point_user', to='app.order'),
        ),
        migrations.AddField(
            model_name='creditpointrequest',
            name='order_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_point_order', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='creditpointrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditpointpayment',
            name='order_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_point_order_payment', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='creditpointpayment',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrer_credit_point_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditpointearning',
            name='order_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_point_earnings', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='creditpointearning',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_point_earning_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditpoint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyusdcreditpoint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usd_cps_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buycreditpoint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_credit_point_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
