# Generated by Django 4.2.3 on 2024-07-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_point', '0002_alter_sellcreditpoint_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adchargecreditpoint',
            name='ad_charge_cps_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='buycreditpoint',
            name='cps_purchase_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='buyusdcreditpoint',
            name='usd_cps_purchase_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cpsbonus',
            name='cps_bonus_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sellcreditpoint',
            name='cps_sell_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
