# Generated by Django 3.2.20 on 2024-01-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_point', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycreditpoint',
            name='cps_purchase_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
