# Generated by Django 4.2.3 on 2024-08-12 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit_point', '0003_alter_adchargecreditpoint_ad_charge_cps_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycreditpoint',
            name='amount',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyusdcreditpoint',
            name='amount',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SellCpsToSellangle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=50)),
                ('paysofter_account_id', models.CharField(blank=True, max_length=50)),
                ('paysofter_seller_id', models.CharField(blank=True, max_length=50)),
                ('cps_sell_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('buyer_old_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('buyer_new_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seller_old_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seller_new_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_cps_to_sellangle_buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssell_cps_to_sellangle_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
