# Generated by Django 3.2.20 on 2024-02-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_point', '0003_alter_buycreditpoint_cps_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycreditpoint',
            name='new_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buycreditpoint',
            name='old_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buyusdcreditpoint',
            name='new_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buyusdcreditpoint',
            name='old_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sellcreditpoint',
            name='new_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sellcreditpoint',
            name='old_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
