# Generated by Django 3.2.20 on 2024-02-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_point', '0004_auto_20240205_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellcreditpoint',
            old_name='new_bal',
            new_name='buyer_new_bal',
        ),
        migrations.RenameField(
            model_name='sellcreditpoint',
            old_name='old_bal',
            new_name='buyer_old_bal',
        ),
        migrations.AddField(
            model_name='sellcreditpoint',
            name='seller_new_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sellcreditpoint',
            name='seller_old_bal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
