# Generated by Django 3.2.20 on 2024-02-15 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit_point', '0005_auto_20240205_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdChargeCreditPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cps_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('ad_charge_cps_id', models.CharField(max_length=10, unique=True)),
                ('old_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_bal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_charge_credit_point_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
