# Generated by Django 4.2.3 on 2024-08-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_point', '0007_sellcpstosellangle_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellcpstosellangle',
            name='cps_checkout_link',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='sellcpstosellangle',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
