# Generated by Django 4.2.3 on 2024-08-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_point', '0008_sellcpstosellangle_cps_checkout_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellcpstosellangle',
            name='paysofter_promise_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
