# Generated by Django 4.2.3 on 2024-08-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_point', '0009_sellcpstosellangle_paysofter_promise_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellcpstosellangle',
            name='paysofter_promise_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
