# Generated by Django 4.2.3 on 2024-10-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_point', '0010_alter_sellcpstosellangle_paysofter_promise_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpsbonus',
            name='cps_bonus_type',
            field=models.CharField(blank=True, choices=[('Referral Bonus', 'Referral Bonus'), ('Followers Bonus', 'Followers Bonus'), ('Sign-up Bonus', 'Sign-up Bonus'), ('Birthday Bonus', 'Birthday Bonus'), ('Loyalty Bonus', 'Loyalty Bonus'), ('Earned Bonus', 'Earned Bonus'), ('Other Bonus', 'Other Bonus')], editable=False, max_length=100, null=True),
        ),
    ]
